apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
        - containerPort: 22
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://192.168.56.111:8080'
            gitlab_rails['gitlab_host'] = '192.168.56.111'
            gitlab_rails['gitlab_port'] = 8080
            gitlab_rails['gitlab_https'] = false
            nginx['listen_port'] = 80
            nginx['listen_https'] = false
            nginx['redirect_http_to_https'] = false
            gitlab_rails['gitlab_ssh_host'] = '192.168.56.111'
            gitlab_rails['gitlab_ssh_port'] = 2222
            # Disable problematic features for stability
            gitlab_rails['gitlab_signup_enabled'] = false
            gitlab_rails['gravatar_enabled'] = false
            gitlab_workhorse['enable'] = true
            sidekiq['enable'] = true
            # Reduce resource usage
            postgresql['shared_buffers'] = "128MB"
            postgresql['max_connections'] = 100
            # Additional memory optimizations
            puma['worker_processes'] = 1
            puma['min_threads'] = 1
            puma['max_threads'] = 2
            sidekiq['max_concurrency'] = 5
            gitaly['env'] = {
              'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '1'
            }
            # Disable memory-intensive features
            prometheus_monitoring['enable'] = false
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
        volumeMounts:
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
        - name: gitlab-config
          mountPath: /etc/gitlab
      volumes:
      - name: gitlab-data
        emptyDir: {}
      - name: gitlab-logs
        emptyDir: {}
      - name: gitlab-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30888
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    app: gitlab
