apiVersion: v1
kind: Service
metadata:
  name: gitlab-webservice-external
  namespace: gitlab
  labels:
    app: gitlab-webservice-external
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: webservice
    gitlab.com/webservice-name: default
    release: gitlab