apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Chane url
    repoURL: 'http://gitlab.192.168.56.111.nip.io:8080/root/wil-app.git'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true      # Delete resources 
      selfHeal: true   # Corrige cambios manuales en el cluster
    syncOptions:
      - CreateNamespace=true  # Crea el namespace si no existe