Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  
    config.vm.define "adiaz-ufS" do |server|
      server.vm.hostname = "adiaz-ufS"
      server.vm.provider "virtualbox" do |vb|
        vb.name = "adiaz-ufS"
      end
  
      server.vm.box = "bento/debian-12"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provision "shell", path: "./scripts/setup.sh"
      server.vm.provision "shell", path: "./scripts/deploy.sh"
    end
end