Vagrant.configure("2") do |config|
    username = `whoami`.strip
    config.vm.synced_folder "./confs", "/vagrant_shared"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
  
    config.vm.define "adiaz-ufS" do |server|
      server.vm.hostname = "adiaz-ufS"
      server.vm.provider "virtualbox" do |vb|
        vb.name = "adiaz-ufS"
      end
  
      server.vm.box = "bento/debian-12"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provision "shell", path: "./scripts/k3s-server.sh", args: ['192.168.56.110']
    end
  
    config.vm.define "alaparicSW" do |worker|
      worker.vm.hostname = "alaparicSW"
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "alaparicSW"
      end
  
      worker.vm.box = "bento/debian-12"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provision "shell", path: "./scripts/k3s-worker.sh", args: ['192.168.56.110']
    end
  end
  