# GitLab Helm Chart Values - Working Configuration
# Optimized for development environment with proper external URL

global:
  hosts:
    domain: 192.168.56.111
    externalIP: 192.168.56.111
    gitlab:
      name: 192.168.56.111
      https: false
  edition: ce
  
  # Disable problematic features
  ingress:
    enabled: false
    configureCertmanager: false
    tls:
      enabled: false
  
  # Minimal resource usage
  nodeSelector: {}

# Disable ALL non-essential services for stability
gitlab-runner:
  install: false

certmanager-issuer:
  email: admin@example.com

nginx-ingress:
  enabled: false
  
prometheus:
  install: false

grafana:
  enabled: false

registry:
  enabled: false

# Minimal persistence
redis:
  persistence:
    size: 1Gi
    
postgresql:
  persistence:
    size: 2Gi

# GitLab configuration with proper external URL
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      limits:
        memory: 2.5Gi
        cpu: 1000m
      requests:
        memory: 1Gi
        cpu: 500m
    ingress:
      enabled: false
    # Adjust probes for slower startup
    deployment:
      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 20
        timeoutSeconds: 60
        failureThreshold: 10
      readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 30
        failureThreshold: 10
      
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 1Gi
        cpu: 500m
    # More generous probes for sidekiq
    deployment:
      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 20
        timeoutSeconds: 60
        failureThreshold: 10
      readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 30
        failureThreshold: 10

  gitaly:
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m