# GitLab Helm Chart Values - Minimal Stable Configuration
# Optimized for development environment with maximum stability

global:
  hosts:
    domain: 192.168.56.111.nip.io
    externalIP: 192.168.56.111
  edition: ce
  
  # Disable problematic features
  ingress:
    enabled: false
    configureCertmanager: false
    tls:
      enabled: false
  
  # Minimal resource usage
  nodeSelector: {}

# Disable ALL non-essential services for stability
gitlab-runner:
  install: false

certmanager-issuer:
  email: admin@example.com

nginx-ingress:
  enabled: false
  
prometheus:
  install: false

grafana:
  enabled: false

registry:
  enabled: false

# Minimal persistence
redis:
  persistence:
    size: 1Gi
    
postgresql:
  persistence:
    size: 2Gi

# Minimal GitLab configuration
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m
    ingress:
      enabled: false
      
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      limits:
        memory: 512Mi
        cpu: 250m
      requests:
        memory: 256Mi
        cpu: 125m