version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 192.168.56.111
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.56.111:8080'
        gitlab_rails['gitlab_host'] = '192.168.56.111'
        gitlab_rails['gitlab_port'] = 8080
        gitlab_rails['gitlab_https'] = false
        nginx['listen_port'] = 8080
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
        gitlab_rails['gitlab_ssh_host'] = '192.168.56.111'
        gitlab_rails['gitlab_ssh_port'] = 2222
    ports:
      - '8080:8080'
      - '2222:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  gitlab:
    driver: bridge
