Vagrant.configure("2") do |config|
  config.vm.define "iot-gitlab" do |server|
    server.vm.hostname = "iot-gitlab"
    server.vm.box = "bento/debian-12"
    server.vm.network "private_network", ip: "192.168.56.111"

    server.vm.synced_folder "./confs", "/home/vagrant/confs"
    server.vm.synced_folder "./gitlab", "/home/vagrant/gitlab"
    server.vm.synced_folder "./scripts", "/home/vagrant/scripts"

    # Make scripts executable after syncing
    server.vm.provision "shell", inline: "chmod +x /home/vagrant/scripts/*.sh"
    
    server.vm.provision "shell", path: "./scripts/setup.sh"
    server.vm.provision "shell", path: "./scripts/deploy.sh"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "iot-gitlab"
      vb.memory = 6144
      vb.cpus = 4
    end
  end
end
