Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "iot-argocd" do |server|
    server.vm.hostname = "iot-argocd"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "iot-argocd"
    end

    server.vm.box = "bento/debian-12"
    server.vm.network "private_network", ip: "192.168.56.110"

    # Provision scripts
    server.vm.provision "shell", path: "./scripts/setup.sh"
    server.vm.provision "shell", path: "./scripts/deploy.sh"
  end
end
